# DS4B 201-P: MACHINE LEARNING WITH PYTHON ----
# Environment Setup ----

# 1. Create an empty conda env ----
#  - Using an environment.yml file with conda
#  - Important Terminal Commands:
#     conda env create -f environment.yml
# 
# 2. Activate the Environment
#  - Command Palette > Python Select Interpreter
#  - Select ds4b_201_p environment
#  - May need to refresh
# 
# 3. Trash Any Open Terminals (Open a New Terminal)
#   
# 4. Pip Install Requirements (Will take 10 minutes or so)
#   - pip install -r requirements.txt
#   - In the event of any errors: Relax requirements and rerun: 
#       pip install -r requirements.txt


name: ds4b_201_p
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pip
